import type { AppManifest } from '../../entities/app/types';

export const appManifests: AppManifest[] = [
  {
    appId: 'material-recommend',
    projectId: 'NM-AI-013',
    name: '非金属智能选材工具',
    shortName: '智能选材',
    category: '选材推荐',
    description: '根据零件、系统、性能需求与风险约束推荐候选材料与牌号。',
    entryType: 'embed',
    routePath: '/apps/material-recommend',
    externalUrl: 'http://pc-ylx46ycr:5176/',
    status: 'active',
    riskLevel: 'R2',
    priority: 'P0',
    tags: ['选材', '推荐', '风险规避'],
    visibleInCatalog: true,
    visibleOnHome: true,
    supportsQueryParams: true,
    supportedParams: ['part_name', 'vehicle_system', 'performance_requirements', 'target_goal'],
  },
  {
    appId: 'vehicle-analysis',
    projectId: 'NM-AI-012',
    name: '整车选材分析系统',
    shortName: '整车选材分析',
    category: '选材推荐',
    description: '从整车、系统、零件维度分析非金属材料应用情况。',
    entryType: 'embed',
    routePath: '/apps/vehicle-analysis',
    externalUrl: 'http://localhost:3000/',
    status: 'available',
    riskLevel: 'R2',
    priority: 'P0',
    tags: ['整车', '系统分析', '用材分析'],
    visibleInCatalog: true,
    visibleOnHome: true,
  },
  {
    appId: 'weight-cost-analysis',
    projectId: 'NM-AI-006',
    name: '非金属零部件减重降本自动分析工具',
    shortName: '减重降本分析',
    category: '分析仿真',
    description: '分析当前零部件用材的减重降本潜在机会点。',
    entryType: 'embed',
    routePath: '/apps/weight-cost-analysis',
    externalUrl: 'http://localhost:8888/',
    status: 'available',
    riskLevel: 'R2',
    priority: 'P0',
    tags: ['减重', '降本', '优化'],
    visibleInCatalog: true,
    visibleOnHome: true,
  },
  {
    appId: 'rubber-db',
    projectId: 'NM-AI-008',
    name: '橡胶材料数据库',
    shortName: '橡胶数据库',
    category: '知识库',
    description: '查询橡胶材料性能、类型、应用零件和对比结果。',
    entryType: 'redirect',
    routePath: '/apps/rubber-db',
    externalUrl: 'https://tianxingjiantt.github.io/rubber-materials/',
    status: 'active',
    riskLevel: 'R1',
    priority: 'P0',
    tags: ['橡胶', '数据库', '查询'],
    visibleInCatalog: true,
    visibleOnHome: true,
  },
  {
    appId: 'supplier-extract',
    projectId: 'NM-AI-002',
    name: '非金属材料分供方提取系统',
    shortName: '分供方提取',
    category: '数据采集',
    description: '提取分供方清单中的材料、牌号、供应商等结构化信息。',
    entryType: 'embed',
    routePath: '/apps/supplier-extract',
    externalUrl: 'http://pc-5cd5483h9y:5000/',
    status: 'available',
    riskLevel: 'R2',
    priority: 'P0',
    tags: ['供应商', '提取', '清单解析'],
    visibleInCatalog: true,
    visibleOnHome: true,
  },
  {
    appId: 'nvh-mass-analysis',
    projectId: 'NM-AI-003',
    name: '以塑代钢-理论质量分析系统',
    shortName: '理论质量分析',
    category: '分析仿真',
    description: '进行理论质量与NVH相关分析。',
    entryType: 'embed',
    routePath: '/apps/nvh-mass-analysis',
    externalUrl: 'http://10.245.137.27:8080/nvh-calculator.html',
    status: 'available',
    riskLevel: 'R2',
    priority: 'P1',
    visibleInCatalog: true,
  },
  {
    appId: 'spectrum-analysis',
    projectId: 'NM-AI-005',
    name: '智能谱图分析系统',
    shortName: '谱图分析',
    category: '分析仿真',
    description: '支持 FTIR、DSC、TGA 等谱图分析与线索提取。',
    entryType: 'embed',
    routePath: '/apps/spectrum-analysis',
    externalUrl: 'http://localhost:5173/',
    status: 'available',
    riskLevel: 'R2',
    priority: 'P1',
    visibleInCatalog: true,
  },
  {
    appId: 'emi-simulator',
    projectId: 'NM-AI-007',
    name: '电磁屏蔽效能仿真工具',
    shortName: 'EMI仿真',
    category: '分析仿真',
    description: '面向高分子材料配方设计辅助的 EMI 理论分析。',
    entryType: 'embed',
    routePath: '/apps/emi-simulator',
    externalUrl: 'http://127.0.0.1:8889/emi-shield-simulator/emi_shield_simulator.html',
    status: 'available',
    riskLevel: 'R2',
    priority: 'P2',
    visibleInCatalog: true,
  },
  {
    appId: 'budget-management',
    projectId: 'NM-AI-004',
    name: '非金属预算管理系统',
    shortName: '预算管理',
    category: '业务管理',
    description: '面向非金属预算统计和管理。',
    entryType: 'embed',
    routePath: '/apps/budget-management',
    externalUrl: 'http://localhost:5000/',
    status: 'available',
    riskLevel: 'R3',
    priority: 'P2',
    visibleInCatalog: true,
  },
  {
    appId: 'solution-management',
    projectId: 'NM-AI-010',
    name: '减重降本方案智能管理系统',
    shortName: '方案管理',
    category: '业务管理',
    description: '智能化记录、追踪新材料方案实施进展。',
    entryType: 'redirect',
    routePath: '/apps/solution-management',
    externalUrl: 'https://tianxingjiantt.github.io/chinaplas-materials/',
    status: 'active',
    riskLevel: 'R3',
    priority: 'P2',
    visibleInCatalog: true,
  },
  {
    appId: 'task-manager',
    projectId: 'NM-AI-014',
    name: '代办管理器',
    shortName: '代办管理',
    category: '业务管理',
    description: '针对多个项目的各工作节点进行管理。',
    entryType: 'embed',
    routePath: '/apps/task-manager',
    externalUrl: 'http://10.245.137.181:3000',
    status: 'available',
    riskLevel: 'R3',
    priority: 'P2',
    visibleInCatalog: true,
  },
  {
    appId: 'trend-insight',
    projectId: 'NM-AI-011',
    name: '非金属前瞻感知系统',
    shortName: '前瞻感知',
    category: '前瞻洞察',
    description: '自动抓取行业前瞻技术信息并生成摘要总结。',
    entryType: 'embed',
    routePath: '/apps/trend-insight',
    externalUrl: 'http://127.0.0.1:5000/bookmark',
    status: 'available',
    riskLevel: 'R4',
    priority: 'P1',
    visibleInCatalog: true,
  },
  {
    appId: 'learning-center',
    projectId: 'NM-AI-001',
    name: '汽车及智能穿戴材料学习平台',
    shortName: '学习平台',
    category: '学习培训',
    description: '针对校招生或刚入职同事进行系统性的学习及培训。',
    entryType: 'native',
    routePath: '/home',
    status: 'active',
    riskLevel: 'R1',
    priority: 'P2',
    visibleInCatalog: true,
  },
  {
    appId: 'dvp-training',
    projectId: 'NM-AI-009',
    name: '项目DVP审核策略培训系统',
    shortName: 'DVP培训',
    category: '学习培训',
    description: '将 DVP 审核策略以智能化与可视化方式展示。',
    entryType: 'redirect',
    routePath: '/apps/dvp-training',
    externalUrl: 'https://tianxingjiantt.github.io/dvpr-system/',
    status: 'active',
    riskLevel: 'R1',
    priority: 'P2',
    visibleInCatalog: true,
  },
];
