import type { CapabilityDefinition } from '../../entities/capability/types';

export const capabilityRegistry: CapabilityDefinition[] = [
  {
    capabilityId: 'material_recommend',
    projectId: 'NM-AI-013',
    appId: 'material-recommend',
    name: '非金属智能选材推荐',
    category: '选材推荐',
    description: '根据零件、系统、性能需求和风险约束推荐候选材料与牌号。',
    intentTags: ['选材', '材料推荐', '牌号推荐', '风险规避'],
    triggerPhrases: ['推荐材料', '帮我选材', '选什么材料', '推荐牌号'],
    requiredParams: ['part_name'],
    optionalParams: [
      'vehicle_system',
      'performance_requirements',
      'risk_focus',
      'material_class',
      'target_goal',
    ],
    invokeType: 'url_jump',
    invokeTarget: '/apps/material-recommend',
    riskLevel: 'R2',
    costHint: 'low',
    latencyHint: 'fast',
    outputType: 'recommendation',
    aiSuitability: 'high',
    supportsSummary: true,
    supportsCrossLink: true,
    nextCapabilities: ['weight_cost_analysis', 'rubber_db_search', 'supplier_extract'],
    status: 'active',
  },
  {
    capabilityId: 'vehicle_material_analysis',
    projectId: 'NM-AI-012',
    appId: 'vehicle-analysis',
    name: '整车选材分析',
    category: '选材推荐',
    description: '从整车、系统、零件维度分析非金属材料应用情况与潜在问题。',
    intentTags: ['整车选材', '系统分析', '零件分析'],
    triggerPhrases: ['整车选材分析', '这个系统用了什么材料', '看下这个零件用材'],
    requiredParams: ['part_name'],
    optionalParams: ['vehicle_system', 'sub_system', 'project_name'],
    invokeType: 'url_jump',
    invokeTarget: '/apps/vehicle-analysis',
    riskLevel: 'R2',
    costHint: 'low',
    latencyHint: 'fast',
    outputType: 'table',
    aiSuitability: 'high',
    supportsSummary: true,
    supportsCrossLink: true,
    nextCapabilities: ['material_recommend', 'weight_cost_analysis'],
    status: 'active',
  },
  {
    capabilityId: 'weight_cost_analysis',
    projectId: 'NM-AI-006',
    appId: 'weight-cost-analysis',
    name: '非金属减重降本分析',
    category: '分析仿真',
    description: '分析当前零部件用材的减重降本潜在机会点，并给出候选替代方案。',
    intentTags: ['减重', '降本', '优化机会', '替代方案'],
    triggerPhrases: ['有没有减重机会', '有没有降本空间', '帮我分析减重降本'],
    requiredParams: ['part_name'],
    optionalParams: ['vehicle_system', 'material_name', 'cost_target', 'weight_target'],
    invokeType: 'url_jump',
    invokeTarget: '/apps/weight-cost-analysis',
    riskLevel: 'R2',
    costHint: 'medium',
    latencyHint: 'medium',
    outputType: 'recommendation',
    aiSuitability: 'high',
    supportsSummary: true,
    supportsCrossLink: true,
    nextCapabilities: ['supplier_extract', 'rubber_db_search'],
    status: 'active',
  },
  {
    capabilityId: 'rubber_db_search',
    projectId: 'NM-AI-008',
    appId: 'rubber-db',
    name: '橡胶材料数据库查询',
    category: '知识库',
    description: '查询橡胶材料性能、类型、应用零件和对比结果。',
    intentTags: ['橡胶材料', '性能查询', '材料对比', '知识查询'],
    triggerPhrases: ['查橡胶材料', '看看EPDM性能', '对比橡胶材料'],
    requiredParams: ['material_name'],
    optionalParams: ['part_category', 'material_class'],
    invokeType: 'url_jump',
    invokeTarget: '/apps/rubber-db',
    riskLevel: 'R1',
    costHint: 'low',
    latencyHint: 'fast',
    outputType: 'table',
    aiSuitability: 'high',
    supportsSummary: true,
    supportsCrossLink: true,
    nextCapabilities: ['material_recommend', 'supplier_extract'],
    status: 'active',
  },
  {
    capabilityId: 'supplier_extract',
    projectId: 'NM-AI-002',
    appId: 'supplier-extract',
    name: '分供方材料提取',
    category: '数据采集',
    description: '提取分供方清单中的材料、牌号、供应商等结构化信息。',
    intentTags: ['供应商', '分供方', '材料提取', '清单解析'],
    triggerPhrases: ['提取分供方', '看看有哪些供应商', '解析材料清单'],
    requiredParams: [],
    optionalParams: ['material_name', 'grade_name', 'supplier_name', 'part_name'],
    invokeType: 'url_jump',
    invokeTarget: '/apps/supplier-extract',
    riskLevel: 'R2',
    costHint: 'medium',
    latencyHint: 'medium',
    outputType: 'table',
    aiSuitability: 'high',
    supportsSummary: true,
    supportsCrossLink: true,
    nextCapabilities: ['material_recommend', 'weight_cost_analysis'],
    status: 'active',
  },
];
